### ISSUE TITLE
UR displayed in QR code includes whitespace.

### ISSUE THREAD

**Issue by wolfmcnally** [BlockchainCommons/GordianQRTool-iOS#55]
Refer to:
https://github.com/BlockchainCommons/GordianGuardian-iOS/issues/51

**Comment by Fonta1n3** [comment]
Its my understanding the issue is there is a whitespace in the QR Gordian Wallet is producing. This is the wrong repo to be raising this. [https://github.com/BlockchainCommons/GordianWallet-iOS/issues/122](https://github.com/BlockchainCommons/GordianWallet-iOS/issues/122) is where I have raised this.
